# Generated by Django 3.2.15 on 2022-11-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField(default='')),
                ('spotify_id', models.TextField(default='')),
                ('follower_total', models.IntegerField(default=0)),
                ('api_access', models.TextField(default='')),
                ('avatar_url', models.TextField(default='')),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expires',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharify.spotifyprofile'),
        ),
    ]
