# Generated by Django 4.1.1 on 2022-12-04 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='num_tracks',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='url',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
