# Generated by Django 3.2.15 on 2022-12-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_are_public',
            field=models.BooleanField(default=True),
        ),
    ]
