# Generated by Django 3.2.15 on 2022-10-31 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dob',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
