# Generated by Django 3.2.15 on 2022-11-05 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_spotify_fav_artist',
            new_name='fav_artist',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_spotify_friends',
            new_name='friends',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_is_paired',
            new_name='is_paired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_spotify_id',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='images/avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 18, 43, 6, 654945, tzinfo=utc)),
        ),
    ]
