# Generated by Django 3.2.15 on 2022-12-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0002_alter_comment_comment_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='on_type',
            field=models.TextField(default='track'),
        ),
    ]
