# Generated by Django 3.2.15 on 2022-11-05 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0002_auto_20221105_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
