# Generated by Django 3.2.15 on 2022-11-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0002_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_artist',
        ),
    ]
