# Generated by Django 3.2.15 on 2022-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0002_auto_20221109_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='spotifyprofile',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_paired',
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='token_info',
            field=models.TextField(default=''),
        ),
    ]
