# Generated by Django 4.1.1 on 2022-12-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0002_remove_playlist_featured_remove_playlist_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.JSONField(default=list),
        ),
    ]
