# Generated by Django 4.1.1 on 2022-12-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0003_user_playlists_are_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_songs',
            field=models.JSONField(default=list),
        ),
    ]
