# Generated by Django 3.2.15 on 2022-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0003_auto_20221109_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyprofile',
            name='token_info',
            field=models.JSONField(default=''),
        ),
    ]
