# Generated by Django 4.1.1 on 2022-11-07 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0003_alter_user_token_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('access_token_expiration_epoch', models.DateField(blank=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='user_dob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_paired',
            new_name='user_is_paired',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fav_artist',
            new_name='user_spotify_fav_artist',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='friends',
            new_name='user_spotify_friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharify.usertoken'),
        ),
    ]
