# Generated by Django 3.2.15 on 2022-10-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
