# Generated by Django 3.2.15 on 2022-11-11 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0004_alter_spotifyprofile_token_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.TextField(default='track')),
                ('comment', models.TextField(default='')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sharify.musicdata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
