# Generated by Django 4.1.1 on 2022-11-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0004_usertoken_rename_bio_user_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='access_token_expiration_epoch',
            field=models.IntegerField(blank=True),
        ),
    ]
