# Generated by Django 4.1.1 on 2022-11-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0005_alter_usertoken_access_token_expiration_epoch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_token',
        ),
        migrations.AddField(
            model_name='user',
            name='user_spotify_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
