# Generated by Django 3.2.15 on 2022-12-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharify', '0006_alter_playlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicdata',
            name='id',
        ),
    ]
